name: Build and deploy Node.js app to Azure Web App - bitbash

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest         # Linux is faster & cheaper than Windows
    permissions:
      contents: read

    defaults:
      run:
        working-directory: src-react   # <— All npm commands run inside this folder

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and build
        run: |
          npm ci
          npm run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: src-react             # <— Upload the built Next.js app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_361A0A60B01145FCB91865D2EA23106B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0CDF13863F864737BAA85ED774CDDE16 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1665A5DF244F4B9CB8B30A081640BC52 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bitbash'
          slot-name: 'staging'
          package: .                 # Deploy the artifact root (contains Next.js build)