name: Build and deploy Node.js app to Azure Web App - bitbash

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: src-react

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 

      - name: Install and build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

    # Create a clean deploy folder with only what the app needs at runtime
      - name: Create deploy bundle
        run: |
          rm -rf ../deploy && mkdir -p ../deploy
          cp -r .next ../deploy/.next
          cp package.json ../deploy/package.json
          cp pnpm-lock.yaml ../deploy/pnpm-lock.yaml
          cp server.js ../deploy/server.js
          cp web.config ../deploy/web.config
          # include static assets if used
          if [ -d public ]; then cp -r public ../deploy/public; fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy  # <-- upload the clean bundle, not the whole src

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_361A0A60B01145FCB91865D2EA23106B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0CDF13863F864737BAA85ED774CDDE16 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1665A5DF244F4B9CB8B30A081640BC52 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bitbash'
          slot-name: 'staging'
          package: .